# Generated by Django 5.0.7 on 2024-08-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
