# Generated by Django 5.0.7 on 2024-08-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_animal_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
    ]
