# Generated by Django 5.0.7 on 2024-08-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_remove_ticket_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
