# Generated by Django 5.0.7 on 2024-08-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.TextField()),
                ('points', models.JSONField()),
            ],
        ),
    ]
